2025-05-12 07:10:54,033 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-12 07:10:54,033 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-12 07:10:54,033 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-12 07:10:54,529 - uvicorn.error - INFO - Started server process [9]
2025-05-12 07:10:54,530 - uvicorn.error - INFO - Waiting for application startup.
2025-05-12 07:10:54,530 - uvicorn.error - INFO - Application startup complete.
2025-05-12 07:11:05,603 - main - INFO - Попытка входа пользователя: grigory
2025-05-12 07:11:05,644 - main - INFO - Успешный вход пользователя: grigory
2025-05-12 07:11:05,697 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:11:07,502 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:11:16,774 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:11:17,530 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:11:23,671 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:11:26,354 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:13:19,804 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:13:23,274 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:13:24,326 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:13:26,975 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:13:32,455 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:13:57,925 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:14:01,177 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:14:16,750 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:14:23,071 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:14:25,485 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:18:27,877 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:31:41,479 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:31:58,298 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:31:59,198 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:32:03,128 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:32:29,173 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:32:45,132 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:32:56,551 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:33:06,682 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:34:11,046 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:34:14,460 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:36:13,558 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:36:17,871 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:36:56,555 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:36:57,681 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 07:37:02,395 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 12:42:09,243 - main - INFO - Попытка входа пользователя: grigory
2025-05-12 12:42:09,248 - main - INFO - Успешный вход пользователя: grigory
2025-05-12 12:42:09,376 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 12:42:10,735 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 12:42:16,515 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 12:47:29,381 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 12:47:32,018 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 12:47:32,826 - main - INFO - Запрос профиля пользователя: grigory
2025-05-12 12:48:42,276 - uvicorn.error - INFO - Shutting down
2025-05-12 12:48:42,380 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-12 12:48:42,380 - uvicorn.error - INFO - Application shutdown complete.
2025-05-12 12:48:42,380 - uvicorn.error - INFO - Finished server process [9]
2025-05-12 12:48:42,471 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 07:47:30,464 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 07:47:30,465 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 07:47:30,465 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 07:47:30,858 - uvicorn.error - INFO - Started server process [9]
2025-05-13 07:47:30,858 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 07:47:30,858 - uvicorn.error - INFO - Application startup complete.
2025-05-13 07:47:53,540 - main - INFO - Попытка входа пользователя: grigory
2025-05-13 07:47:53,583 - main - INFO - Успешный вход пользователя: grigory
2025-05-13 07:47:53,646 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 07:47:54,750 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 07:48:05,552 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 07:48:06,478 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 07:53:08,729 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 07:54:10,732 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 07:55:01,139 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:00:14,683 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:04:07,705 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:04:41,873 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:04:42,958 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:05:00,579 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:05:01,247 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:05:58,622 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 545, in _prepare_and_execute
    self._rows = deque(await prepared_stmt.fetch(*parameters))
  File "/usr/local/lib/python3.9/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
  File "/usr/local/lib/python3.9/site-packages/asyncpg/prepared_stmt.py", line 267, in __bind_execute
    data, status, _ = await self.__do_execute(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/prepared_stmt.py", line 256, in __do_execute
    return await executor(protocol)
  File "asyncpg/protocol/protocol.pyx", line 206, in bind_execute
asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "questions_pkey"
DETAIL:  Key (id)=(4) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 580, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 558, in _prepare_and_execute
    self._handle_exception(error)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 508, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 792, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.IntegrityError: <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "questions_pkey"
DETAIL:  Key (id)=(4) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/main.py", line 178, in create_question
    await session.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 1015, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4353, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4489, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4449, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 580, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 558, in _prepare_and_execute
    self._handle_exception(error)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 508, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 792, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "questions_pkey"
DETAIL:  Key (id)=(4) already exists.
[SQL: INSERT INTO questions (question_text, is_there_media, media_url, user_id, created_at) VALUES ($1::VARCHAR, $2::BOOLEAN, $3::VARCHAR, $4::INTEGER, $5::TIMESTAMP WITHOUT TIME ZONE) RETURNING questions.id]
[parameters: ('Новый вопрос', False, None, None, datetime.datetime(2025, 5, 13, 8, 5, 58, 611922))]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-05-13 08:06:08,329 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 545, in _prepare_and_execute
    self._rows = deque(await prepared_stmt.fetch(*parameters))
  File "/usr/local/lib/python3.9/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
  File "/usr/local/lib/python3.9/site-packages/asyncpg/prepared_stmt.py", line 267, in __bind_execute
    data, status, _ = await self.__do_execute(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/prepared_stmt.py", line 256, in __do_execute
    return await executor(protocol)
  File "asyncpg/protocol/protocol.pyx", line 206, in bind_execute
asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "questions_pkey"
DETAIL:  Key (id)=(5) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 580, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 558, in _prepare_and_execute
    self._handle_exception(error)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 508, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 792, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.IntegrityError: <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "questions_pkey"
DETAIL:  Key (id)=(5) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/main.py", line 178, in create_question
    await session.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 1015, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4353, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4489, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4449, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 580, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 558, in _prepare_and_execute
    self._handle_exception(error)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 508, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 792, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "questions_pkey"
DETAIL:  Key (id)=(5) already exists.
[SQL: INSERT INTO questions (question_text, is_there_media, media_url, user_id, created_at) VALUES ($1::VARCHAR, $2::BOOLEAN, $3::VARCHAR, $4::INTEGER, $5::TIMESTAMP WITHOUT TIME ZONE) RETURNING questions.id]
[parameters: ('Новый вопрос', False, None, None, datetime.datetime(2025, 5, 13, 8, 6, 8, 324141))]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-05-13 08:12:48,715 - uvicorn.error - INFO - Shutting down
2025-05-13 08:12:48,817 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 08:12:48,817 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 08:12:48,818 - uvicorn.error - INFO - Finished server process [9]
2025-05-13 08:12:48,892 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 08:12:50,048 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 08:12:50,049 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 08:12:50,049 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 08:12:50,450 - uvicorn.error - INFO - Started server process [9]
2025-05-13 08:12:50,450 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 08:12:50,451 - uvicorn.error - INFO - Application startup complete.
2025-05-13 08:12:53,928 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:13:03,932 - main - ERROR - Ошибка при создании вопроса: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "questions_pkey"
DETAIL:  Key (id)=(6) already exists.
[SQL: INSERT INTO questions (question_text, is_there_media, media_url, user_id, created_at) VALUES ($1::VARCHAR, $2::BOOLEAN, $3::VARCHAR, $4::INTEGER, $5::TIMESTAMP WITHOUT TIME ZONE) RETURNING questions.id]
[parameters: ('Новый вопрос', False, None, 1, datetime.datetime(2025, 5, 13, 8, 13, 3, 923715))]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-05-13 08:16:11,348 - uvicorn.error - INFO - Shutting down
2025-05-13 08:16:11,450 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 08:16:11,451 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 08:16:11,451 - uvicorn.error - INFO - Finished server process [9]
2025-05-13 08:16:11,506 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 08:16:27,820 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 08:16:27,821 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 08:16:27,821 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 08:16:28,250 - uvicorn.error - INFO - Started server process [9]
2025-05-13 08:16:28,250 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 08:16:28,251 - uvicorn.error - INFO - Application startup complete.
2025-05-13 08:16:40,884 - uvicorn.error - INFO - Shutting down
2025-05-13 08:16:40,988 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 08:16:40,989 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 08:16:40,989 - uvicorn.error - INFO - Finished server process [9]
2025-05-13 08:16:41,044 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 08:16:42,204 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 08:16:42,205 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 08:16:42,205 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 08:16:42,635 - uvicorn.error - INFO - Started server process [8]
2025-05-13 08:16:42,636 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 08:16:42,636 - uvicorn.error - INFO - Application startup complete.
2025-05-13 08:16:46,077 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:16:54,363 - main - ERROR - Ошибка при создании вопроса: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "questions_pkey"
DETAIL:  Key (id)=(7) already exists.
[SQL: INSERT INTO questions (question_text, is_there_media, media_url, user_id, created_at) VALUES ($1::VARCHAR, $2::BOOLEAN, $3::VARCHAR, $4::INTEGER, $5::TIMESTAMP WITHOUT TIME ZONE) RETURNING questions.id]
[parameters: ('hello', False, None, 1, datetime.datetime(2025, 5, 13, 8, 16, 54, 357518))]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-05-13 08:18:21,835 - uvicorn.error - INFO - Shutting down
2025-05-13 08:18:21,938 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 08:18:21,939 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 08:18:21,939 - uvicorn.error - INFO - Finished server process [8]
2025-05-13 08:18:21,996 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 08:18:26,497 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 08:18:26,499 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 08:18:26,499 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 08:18:26,932 - uvicorn.error - INFO - Started server process [9]
2025-05-13 08:18:26,933 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 08:18:26,933 - uvicorn.error - INFO - Application startup complete.
2025-05-13 08:18:34,008 - main - INFO - Попытка входа пользователя: grigory
2025-05-13 08:18:34,056 - main - WARNING - Неудачная попытка входа: неверный пароль для пользователя grigory
2025-05-13 08:18:35,519 - main - INFO - Попытка входа пользователя: grigory
2025-05-13 08:18:35,521 - main - INFO - Успешный вход пользователя: grigory
2025-05-13 08:18:35,654 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:18:36,709 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:18:46,694 - main - ERROR - Ошибка целостности данных при создании вопроса: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "questions_pkey"
DETAIL:  Key (id)=(8) already exists.
[SQL: INSERT INTO questions (question_text, is_there_media, media_url, user_id, created_at) VALUES ($1::VARCHAR, $2::BOOLEAN, $3::VARCHAR, $4::INTEGER, $5::TIMESTAMP WITHOUT TIME ZONE) RETURNING questions.id]
[parameters: ('hello world', False, None, 1, datetime.datetime(2025, 5, 13, 8, 18, 46, 689697))]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-05-13 08:20:44,257 - uvicorn.error - INFO - Shutting down
2025-05-13 08:20:44,360 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 08:20:44,360 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 08:20:44,361 - uvicorn.error - INFO - Finished server process [9]
2025-05-13 08:20:44,421 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 08:20:48,443 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 08:20:48,444 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 08:20:48,444 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 08:20:48,880 - uvicorn.error - INFO - Started server process [9]
2025-05-13 08:20:48,880 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 08:20:48,880 - uvicorn.error - INFO - Application startup complete.
2025-05-13 08:20:53,396 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:23:21,718 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:23:22,747 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:23:34,019 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:23:34,891 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:26:41,250 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:26:44,469 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:26:50,696 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:26:51,689 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:27:01,733 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:27:02,870 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:29:26,306 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:29:27,259 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:29:29,682 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:29:30,752 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:29:34,850 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:29:35,647 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:29:38,001 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:29:38,862 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:29:41,509 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:29:42,332 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:29:47,019 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:29:48,010 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:40:44,500 - uvicorn.error - INFO - Shutting down
2025-05-13 08:40:44,600 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 08:40:44,600 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 08:40:44,600 - uvicorn.error - INFO - Finished server process [9]
2025-05-13 08:40:44,670 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 08:40:56,916 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 08:40:56,917 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 08:40:56,917 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 08:40:57,320 - uvicorn.error - INFO - Started server process [8]
2025-05-13 08:40:57,320 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 08:40:57,320 - uvicorn.error - INFO - Application startup complete.
2025-05-13 08:41:00,093 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:41:01,746 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:41:14,794 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:41:15,883 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:41:17,376 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:41:35,714 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:42:26,156 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:42:27,273 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:42:31,860 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:42:45,869 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:42:46,805 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:42:47,886 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:56:42,828 - main - INFO - Попытка входа пользователя: grigory
2025-05-13 08:56:42,834 - main - INFO - Успешный вход пользователя: grigory
2025-05-13 08:56:42,955 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:56:44,339 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:56:45,321 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:56:45,369 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:56:57,493 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:57:02,043 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:57:49,215 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 08:57:49,263 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:06:43,260 - uvicorn.error - INFO - Shutting down
2025-05-13 09:06:43,360 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 09:06:43,361 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 09:06:43,361 - uvicorn.error - INFO - Finished server process [8]
2025-05-13 09:06:43,438 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 09:06:54,701 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 09:06:54,702 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 09:06:54,702 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 09:06:55,096 - uvicorn.error - INFO - Started server process [9]
2025-05-13 09:06:55,096 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 09:06:55,097 - uvicorn.error - INFO - Application startup complete.
2025-05-13 09:06:58,519 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:07:00,536 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:07:01,598 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:07:04,513 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:07:07,464 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:07:08,827 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:07:15,339 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:07:23,052 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:07:23,705 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:07:29,223 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:07:32,997 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:07:34,152 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:07:37,076 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:08:00,049 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:08:01,131 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:08:12,729 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:08:13,607 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:13:43,867 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:13:56,655 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:14:04,999 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:14:05,704 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:14:57,878 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:15:14,489 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:15:15,859 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:15:17,564 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:15:21,579 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:15:22,472 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:15:39,359 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:18:51,676 - uvicorn.error - INFO - Shutting down
2025-05-13 09:18:51,780 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 09:18:51,780 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 09:18:51,781 - uvicorn.error - INFO - Finished server process [9]
2025-05-13 09:18:51,865 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 09:18:53,151 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 09:18:53,152 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 09:18:53,153 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 09:18:53,564 - uvicorn.error - INFO - Started server process [9]
2025-05-13 09:18:53,565 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 09:18:53,565 - uvicorn.error - INFO - Application startup complete.
2025-05-13 09:18:56,411 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:19:05,667 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:19:06,337 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:19:07,267 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:19:09,342 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:19:10,880 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:19:12,862 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:19:13,566 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:19:14,450 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:19:41,710 - uvicorn.error - INFO - Shutting down
2025-05-13 09:19:41,814 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 09:19:41,814 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 09:19:41,814 - uvicorn.error - INFO - Finished server process [9]
2025-05-13 09:19:41,873 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 09:19:45,675 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 09:19:45,676 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 09:19:45,676 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 09:19:46,079 - uvicorn.error - INFO - Started server process [9]
2025-05-13 09:19:46,080 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 09:19:46,080 - uvicorn.error - INFO - Application startup complete.
2025-05-13 09:19:49,243 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:19:56,527 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:19:58,581 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:19:59,504 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:20:00,579 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:20:24,144 - uvicorn.error - INFO - Shutting down
2025-05-13 09:20:24,250 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 09:20:24,250 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 09:20:24,250 - uvicorn.error - INFO - Finished server process [9]
2025-05-13 09:20:24,304 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 09:20:28,001 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 09:20:28,004 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 09:20:28,004 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 09:20:28,418 - uvicorn.error - INFO - Started server process [9]
2025-05-13 09:20:28,418 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 09:20:28,418 - uvicorn.error - INFO - Application startup complete.
2025-05-13 09:20:30,746 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:20:32,623 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:20:33,404 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:20:34,508 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:20:42,072 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:20:43,300 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:20:44,817 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:20:55,724 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:20:56,397 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:21:01,729 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:24:22,679 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:24:38,691 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:24:41,609 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:29:21,942 - main - INFO - Попытка входа пользователя: grigory
2025-05-13 09:29:21,943 - main - INFO - Успешный вход пользователя: grigory
2025-05-13 09:29:22,091 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:29:23,106 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:29:23,986 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:33:45,398 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:35:50,783 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:36:15,373 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:36:16,492 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:40:26,437 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:40:55,405 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:40:56,874 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 09:41:25,094 - uvicorn.error - INFO - Shutting down
2025-05-13 09:41:25,196 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 09:41:25,196 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 09:41:25,196 - uvicorn.error - INFO - Finished server process [9]
2025-05-13 09:41:25,261 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 13:04:19,491 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 13:04:19,492 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 13:04:19,492 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 13:04:19,949 - uvicorn.error - INFO - Started server process [8]
2025-05-13 13:04:19,949 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 13:04:19,950 - uvicorn.error - INFO - Application startup complete.
2025-05-13 13:04:51,698 - main - INFO - Попытка входа пользователя: grigory
2025-05-13 13:04:51,742 - main - INFO - Успешный вход пользователя: grigory
2025-05-13 13:04:51,839 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:04:53,269 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:05:08,625 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:05:14,624 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:05:57,405 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:06:05,362 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:06:12,598 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:06:18,870 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:07:42,731 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:07:47,906 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:08:01,264 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:08:02,948 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:20:05,727 - uvicorn.error - INFO - Shutting down
2025-05-13 13:20:05,831 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 13:20:05,832 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 13:20:05,833 - uvicorn.error - INFO - Finished server process [8]
2025-05-13 13:20:05,966 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 13:20:07,300 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 13:20:07,301 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 13:20:07,301 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 13:20:07,729 - uvicorn.error - INFO - Started server process [9]
2025-05-13 13:20:07,729 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 13:20:07,730 - uvicorn.error - INFO - Application startup complete.
2025-05-13 13:20:14,514 - main - ERROR - Ошибка при получении списка вопросов: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.PostgresSyntaxError'>: syntax error at or near "questions"
[SQL: SELECT q.id, q.question_text, q.created_at, COUNT(a.id) as answers_count, CASE WHEN qa.question_id IS NULL THEN 'false' ELSE 'true' END as is_solvedFROM questions q LEFT JOIN answers a ON q.id = a.question_id LEFT JOIN user_question_history qa ON q.user_id = qa.user_id GROUP BY q.id, q.question_text, q.created_at ORDER BY q.created_at DESC]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-13 13:20:14,516 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:23:22,933 - uvicorn.error - INFO - Shutting down
2025-05-13 13:23:23,037 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 13:23:23,037 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 13:23:23,037 - uvicorn.error - INFO - Finished server process [9]
2025-05-13 13:23:23,118 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 13:23:26,679 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 13:23:26,680 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 13:23:26,680 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 13:23:27,117 - uvicorn.error - INFO - Started server process [9]
2025-05-13 13:23:27,117 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 13:23:27,118 - uvicorn.error - INFO - Application startup complete.
2025-05-13 13:23:30,360 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:23:30,368 - main - ERROR - Ошибка при получении списка вопросов: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.GroupingError'>: column "qa.question_id" must appear in the GROUP BY clause or be used in an aggregate function
[SQL: SELECT q.id, q.question_text, q.created_at, COUNT(a.id) as answers_count, CASE WHEN qa.question_id IS NOT NULL THEN 'true' ELSE 'false' END as is_solved FROM questions q LEFT JOIN answers a ON q.id = a.question_id LEFT JOIN user_question_history qa ON q.id = qa.question_id AND qa.user_id = $1 GROUP BY q.id, q.question_text, q.created_at ORDER BY q.created_at DESC]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-13 13:23:32,320 - main - ERROR - Ошибка при получении списка вопросов: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.GroupingError'>: column "qa.question_id" must appear in the GROUP BY clause or be used in an aggregate function
[SQL: SELECT q.id, q.question_text, q.created_at, COUNT(a.id) as answers_count, CASE WHEN qa.question_id IS NOT NULL THEN 'true' ELSE 'false' END as is_solved FROM questions q LEFT JOIN answers a ON q.id = a.question_id LEFT JOIN user_question_history qa ON q.id = qa.question_id AND qa.user_id = $1 GROUP BY q.id, q.question_text, q.created_at ORDER BY q.created_at DESC]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-13 13:23:32,323 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:23:33,928 - main - ERROR - Ошибка при получении списка вопросов: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.GroupingError'>: column "qa.question_id" must appear in the GROUP BY clause or be used in an aggregate function
[SQL: SELECT q.id, q.question_text, q.created_at, COUNT(a.id) as answers_count, CASE WHEN qa.question_id IS NOT NULL THEN 'true' ELSE 'false' END as is_solved FROM questions q LEFT JOIN answers a ON q.id = a.question_id LEFT JOIN user_question_history qa ON q.id = qa.question_id AND qa.user_id = $1 GROUP BY q.id, q.question_text, q.created_at ORDER BY q.created_at DESC]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-13 13:23:33,929 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:24:31,300 - uvicorn.error - INFO - Shutting down
2025-05-13 13:24:31,404 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 13:24:31,404 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 13:24:31,404 - uvicorn.error - INFO - Finished server process [9]
2025-05-13 13:24:31,480 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 13:24:34,870 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 13:24:34,871 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 13:24:34,871 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 13:24:35,311 - uvicorn.error - INFO - Started server process [9]
2025-05-13 13:24:35,312 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 13:24:35,312 - uvicorn.error - INFO - Application startup complete.
2025-05-13 13:24:37,976 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:29:11,270 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:29:26,722 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:29:39,820 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:30:14,824 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:30:34,827 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:30:42,659 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:32:54,470 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:32:58,547 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:33:00,542 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:34:31,598 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:34:39,575 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:34:40,945 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:35:21,328 - main - INFO - Попытка входа пользователя: grigory
2025-05-13 13:35:21,333 - main - INFO - Успешный вход пользователя: grigory
2025-05-13 13:35:21,455 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:35:22,587 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:35:24,799 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:35:29,824 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:35:38,611 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:35:56,190 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:35:57,991 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:35:58,642 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:35:59,900 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:10,955 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:14,492 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:15,936 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:17,746 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:20,418 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:22,415 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:24,992 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:27,117 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:29,482 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:33,390 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:35,329 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:37,634 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:39,446 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:41,462 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:53,265 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:54,215 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:36:56,182 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:37:08,274 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:38:40,659 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:38:44,685 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:38:47,531 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:38:49,542 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:38:51,240 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:38:53,003 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:38:55,031 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:40:08,260 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:43:04,201 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:43:05,607 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:43:08,775 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:47:33,291 - uvicorn.error - INFO - Shutting down
2025-05-13 13:47:33,396 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 13:47:33,396 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 13:47:33,396 - uvicorn.error - INFO - Finished server process [9]
2025-05-13 13:47:33,505 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 13:47:38,306 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 13:47:38,307 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 13:47:38,307 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 13:47:38,741 - uvicorn.error - INFO - Started server process [9]
2025-05-13 13:47:38,742 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 13:47:38,742 - uvicorn.error - INFO - Application startup complete.
2025-05-13 13:47:41,445 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:47:49,913 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:47:50,810 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:47:54,985 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:48:08,084 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:48:09,047 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 13:48:10,101 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 14:20:00,353 - uvicorn.error - INFO - Shutting down
2025-05-13 14:20:00,455 - uvicorn.error - INFO - Waiting for application shutdown.
2025-05-13 14:20:00,456 - uvicorn.error - INFO - Application shutdown complete.
2025-05-13 14:20:00,456 - uvicorn.error - INFO - Finished server process [9]
2025-05-13 14:20:00,579 - uvicorn.error - INFO - Stopping reloader process [1]
2025-05-13 14:20:13,806 - uvicorn.error - INFO - Will watch for changes in these directories: ['/app']
2025-05-13 14:20:13,807 - uvicorn.error - INFO - Uvicorn running on https://0.0.0.0:8000 (Press CTRL+C to quit)
2025-05-13 14:20:13,807 - uvicorn.error - INFO - Started reloader process [1] using statreload
2025-05-13 14:20:14,234 - uvicorn.error - INFO - Started server process [9]
2025-05-13 14:20:14,235 - uvicorn.error - INFO - Waiting for application startup.
2025-05-13 14:20:14,235 - uvicorn.error - INFO - Application startup complete.
2025-05-13 14:20:20,617 - main - INFO - Попытка входа пользователя: grigory
2025-05-13 14:20:20,664 - main - INFO - Успешный вход пользователя: grigory
2025-05-13 14:20:20,757 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 14:20:22,764 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 14:20:27,791 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 14:20:43,949 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 14:20:45,222 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 14:20:50,339 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 14:20:56,056 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 14:20:57,226 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 14:21:09,658 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 14:21:11,328 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 14:21:23,498 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 14:21:24,497 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 14:21:28,095 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 14:21:38,621 - main - INFO - Запрос профиля пользователя: grigory
2025-05-13 14:21:41,116 - main - INFO - Запрос профиля пользователя: grigory
